### ISSUE TITLE
If you skip notifications or Locations, you keep getting onboarding over and over

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#771] opened 2020-04-01 05:14 UTC

**Comment by dna-f** [comment] 2020-04-01 06:55
Hi @advayDev1 , that's probably due to the way the onboarding is pushed (during the home page initState)
I add a few comments on this other issue, if it can help
https://github.com/WorldHealthOrganization/app/issues/776

**Comment by dna-f** [comment] 2020-04-01 14:58
Sorry, I misunderstood the problem

**Comment by hspinks** [comment] 2020-04-02 01:19
Assigning to @advayDev1 to see if we can consistently reproduce

**Comment by stevan-milovanovic** [comment] 2020-04-03 19:13
I tested this use case with code from current master branch [app version 0.1.1(2)] and I could not reproduce described behaviour.

**Closed** 2020-04-03 20:21 UTC
Labels: P0, bug, client
