### ISSUE TITLE
slack group joining link of covid-19 app project not working 

### ISSUE THREAD

**Issue by hs663964** [WorldHealthOrganization/app#412] opened 2020-03-27 11:37 UTC
slack group joining link of covid-19 app project not working
link :https://who-app.slack.com/join/shared_invite/zt-cx6ycppt-ccqPJ7ZSGy3~77gSByexJw not working
kindly share new link

**Comment by britannio** [comment] 2020-03-27 11:45
Duplicate of https://github.com/WorldHealthOrganization/app/issues/406

**Closed** 2020-03-27 12:04 UTC
