### ISSUE TITLE
Update PermissionRequestPage Widget

### ISSUE THREAD

**Issue by jasonTelanoff** [WorldHealthOrganization/app#682] opened 2020-03-31 00:47 UTC
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

Onboarding pages do not mach Figma. Text sizes don't match as well as text colors and weight. Padding also needs to be adjusted.

**Comment by am-singh** [comment] 2020-03-31 00:51
part of this is a duplicate of https://github.com/WorldHealthOrganization/app/issues/678

**Comment by jasonTelanoff** [comment] 2020-03-31 01:01
> part of this is a duplicate of #678. Or?

This is not. This has to do with the notifications and location request pages. Also, it addresses the text size, weight, and color, rather than the background color.

**Comment by hspinks** [comment] 2020-04-04 23:17
Closed in #686

**Closed by hspinks** 2020-04-04 23:17 UTC
