### ISSUE TITLE
Add Turkish translation

### ISSUE THREAD

**Issue by kbuyukburc** [WorldHealthOrganization/app#650] opened 2020-03-30 19:20 UTC
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by kbuyukburc** [comment] 2020-03-30 19:28
I am a native Turkish speaker. I can translate intl_en_US.arb . Do I need anything else to approve pull request?

**Comment by advayDev1** [comment] 2020-04-20 03:19
Dupe of #638

**Closed by advayDev1** 2020-04-20 03:19 UTC
Labels: area:l10n, resolved:duplicate
