### ISSUE TITLE
Once a particular country is selected, there is no possibility to choose another one

### ISSUE THREAD

**Issue by kostenkoka** [WorldHealthOrganization/app#1568] opened 2020-10-09 08:24 UTC
**Describe the problem**
Once a particular country is selected, there is no possibility to choose other country

**To Reproduce**

1. Go to 'Recent Numbers > See All' - you'll see your initially selected country
2. Look for a country selection.
3. Error: there is no possibility to select other country (no country selection list)

**Expected, correct behavior**
There should be a possibility to select different countries or to do not select any - display global numbers.
![Capture d’écran   2020-10-09 à 10 17 36](https://user-images.githubusercontent.com/72559155/95560496-a85c1800-0a19-11eb-8863-6e42666e39ca.png)

**Phone/Tablet (please complete the following information):**

- Device:  iPhone7
- OS:  iOS13.7

**Screenshots**

**Comment by borowiecth** [comment] 2020-10-09 13:57
Duplicate with https://github.com/WorldHealthOrganization/app/issues/1573

**Comment by brunobowden** [comment] 2020-10-11 05:12
Duplicate of #1573

**Closed by brunobowden** 2020-10-11 05:12 UTC
Labels: needs:triage, source:who, t:bug
