### ISSUE TITLE
Do we need to use survey-react? Could we just use a simple form?

### ISSUE THREAD

**Issue by pjayathissa** [WorldHealthOrganization/app#115] opened 2020-03-21 09:07 UTC
I was just wondering what the added advantage of using `survey-react` is?

**Comment by SamMousa** [comment] 2020-03-21 09:08
Duplicate of #68

**Comment by SamMousa** [comment] 2020-03-21 09:11
Imo surveys and forms are not the same. Especially when routing becomes more complex using a simple form lib will become cumbersome.

**Closed** 2020-03-21 09:32 UTC
Labels: question
