### ISSUE TITLE
Slack link is wrong

### ISSUE THREAD

**Issue by camillo777** [WorldHealthOrganization/app#411] opened 2020-03-27 11:31 UTC
Slack link is wrong:

https://join.slack.com/t/who-app/shared_invite/zt-cx6ycppt-ccqPJ7ZSGy3~77gSByexJw

On getting started page:

https://worldhealthorganization.github.io/app/ONBOARDING.html

**Comment by SamMousa** [comment] 2020-03-27 11:31
Duplicate of #406

**Closed by SamMousa** 2020-03-27 11:31 UTC
