### ISSUE TITLE
Add style/formatting guide in CONTRIBUTING.md

### ISSUE THREAD

**Issue by json469** [WorldHealthOrganization/app#400] opened 2020-03-27 10:23 UTC
It seems that this project doesn't have a set guideline for style and formatting.
As per discussion [here](https://github.com/WorldHealthOrganization/app/pull/319#discussion_r399161721), I would strongly recommend using the [official Flutter's very own repo style guideline](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo).

We can ensure simplicity by not creating our own (as it takes time and there are always difference in opinions in terms of styling and formatting) while still ensuring a large scope.
I think it would be beneficial for us to make use of what we already have and tested 😄I've done so in couple of projects as well.

**Comment by SamMousa** [comment] 2020-03-27 10:25
Duplicate of #334, which is already implemented in #396

**Closed by SamMousa** 2020-03-27 10:25 UTC

**Comment by json469** [comment] 2020-03-27 10:32
Hey @SamMousa I read that 😄but it took me awhile to search for it by reading through some issues. Would it be helpful if we put that information in the docs for newly contributing developers?

**Comment by SamMousa** [comment] 2020-03-27 11:00
Yes definitely, currently we're just seeing an influx of 100+ new people while also sprinting for an initial release. We unfortunately don't have the resources to spend on this right now.

Note that onboarding already mentions you should be assigned to the issue if you want to work on it, afaik.
Thanks for understanding!

**Comment by json469** [comment] 2020-03-27 12:03
No worries at all! I did notice that and also the spam on LINK NOT WORKING (all caps 🤣), the project is great and love the enthusiasm the Flutter developers bring in. Sure, I will see what I can do thanks 👍
