### ISSUE TITLE
Privacy-focused QA verification (incl on final release build)

### ISSUE THREAD

**Issue by advayDev1** [WorldHealthOrganization/app#1509] opened 2020-09-22 21:54 UTC
Filed as a reminder =)

This includes *but is not limited to* verifying the following in the final build on iOS and Android:
- Ensuring that all opt-outs/opt-ins work as intended.
- Preserving opt-outs across restarts and app updates
- Verifying that nothing leaves the app/device prior to continuing past the initial screen, except and unless it is triaged and accepted by WHO.
- Only the services documented in the Privacy Policy are used.
- Verifying the privacy settings in production match the privacy policy.
- Verifying the retention policies in production match the privacy policy.
- Verifying no identifiers are preserved across installs or devices, including when backup/sync are enabled.

As always this is not legal advice.  And to be clear, with my departure, I'm not doing this verification.
_Please don't edit to signify changes - GitHub makes it appear that such edits come from me.  If your goal is different than what is described here, say so in comments._

**Comment by brunobowden** [comment] 2020-12-19 21:01
I'll be taking this on with the next release.

**Comment by brunobowden** [comment] 2020-12-20 04:40
Verified:
- [x] Preserving opt-outs across restarts and app updates - Tested with Analytics, Notifications & Country Selection across restart and app update to v1.0.0
- [x] Verifying that nothing leaves the app/device prior to continuing past the initial screen, except and unless it is triaged and accepted by WHO.
- [x] Only the services documented in the Privacy Policy are used.
- [x] Verifying the privacy settings in production match the privacy policy.
- [x] Verifying the retention policies in production match the privacy policy.

Working on:
- [ ] Ensuring that all opt-outs/opt-ins work as intended.
- [ ] Verifying no identifiers are preserved across installs or devices, including when backup/sync are enabled.

**Comment by advayDev1** [comment] 2020-12-20 15:12
Since you've punted these bugs past launch:

If notifications opt-out does not work is that not a privacy bug that must be fixed prior to launch to match the privacy policy? #1857  Even if you fix it later before sending a message that could still require later user intervention to honor the already set opt out (like running the updated app).

  Same with opt-in on iOS - users will expect it to get notifications but they will not receive any until some further interaction with updated app. #1855

**Comment by brunobowden** [comment] 2020-12-20 19:58
See [1855 comment](https://github.com/WorldHealthOrganization/app/issues/1855#issuecomment-748657659). Acknowledge the other implications. We'll deal with it as soon as we can.

cc @travelkev

**Comment by brunobowden** [comment] 2020-12-20 20:01
Closing this for launch. Moved unresolved issue of #1862 (identifiers removed after delete) to separate issue to deal with post launch.

**Closed by brunobowden** 2020-12-20 20:01 UTC
Labels: P0, privacy, qa, signoff
