### ISSUE TITLE
Code uses Double Quotes

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [WorldHealthOrganization/app#433] opened 2020-03-27 14:56 UTC
I think that the code should use **single quotes** for strings where possible (where the string itself does not contain single quotes). This would be consistent with the [Flutter Repo Style Guide][].

At least, we should be consistent within this repo and decide to use one over the other.  
I can open a PR to fix this and potentially add this to the Contributing Guides, e.g. that contributors should adhere to the [Flutter Repo Style Guide][] generally.

 [Flutter Repo Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#prefer-single-quotes-for-strings

**Comment by SamMousa** [comment] 2020-03-27 14:57
Duplicate of #334

**Comment by SamMousa** [comment] 2020-03-27 14:58
Someone proposed a set of rules in an issue, but can't find that now. Wait before you implement please!

**Comment by suztomo** [comment] 2020-03-27 15:02
I use this analysis rule "pedantic_mono" that derives from pedantic: https://pub.dev/packages/pedantic_mono . This includes prefer_single_quotes.

ref. https://github.com/WorldHealthOrganization/app/issues/338#issuecomment-604973037

**Comment by SamMousa** [comment] 2020-03-27 15:02
That's what I was looking for!

**Comment by SamMousa** [comment] 2020-03-27 15:03
Closing this one. @creativecreatorormaybenot if you want to implement #338 go ahead, check with @suztomo to make sure you don't both do it. But I think @suztomo won't have time until the weekend.

**Closed by SamMousa** 2020-03-27 15:03 UTC

**Comment by suztomo** [comment] 2020-03-27 15:04
Right. You can take #338 now
