### ISSUE TITLE
Bar chart values is shown with 0 after the coma

### ISSUE THREAD

**Issue by kostenkoka** [WorldHealthOrganization/app#1566] opened 2020-10-09 08:12 UTC
**Describe the problem**
A format of graph value is always shown with 0, e.g. 123333.0 which doesn't bring any insight.

**To Reproduce**

1. Go to 'Recent numbers > See all > Total or Daily'
2. Tap a bar chart to see a value
4. See error: value is always shown with 0, e.g. 123333.0 which doesn't bring any insight.

**Expected, correct behavior**
Bar chart value should be displayed without digits

**Phone/Tablet (please complete the following information):**

- Device: iPhone7
- OS: [e.g. iOS13.7

**Screenshots**

![Capture d’écran   2020-10-09 à 10 02 18](https://user-images.githubusercontent.com/72559155/95559265-c58fe700-0a17-11eb-870c-e007fb93f734.png)

**Comment by borowiecth** [comment] 2020-10-09 14:42
Same as https://github.com/WorldHealthOrganization/app/issues/1563

**Comment by brunobowden** [comment] 2020-10-11 05:20
Duplicate of #1563

**Closed by brunobowden** 2020-10-11 05:20 UTC
Labels: needs:triage, source:who, t:bug
