### ISSUE TITLE
GitHub organisation url

### ISSUE THREAD

**Issue by hugolgst** [WorldHealthOrganization/app#1060] opened 2020-04-17 10:05 UTC
You should change the URL in your GitHub organisation profile: http://worldhealthorganization.github.io
Which is unavailable

**Comment by SamMousa** [comment] 2020-04-17 15:55
There is no content here though. I'm not sure an organisation pages makes sense at this point.

Thanks for the tip, will discuss during standup!

**Comment by hugolgst** [comment] 2020-04-17 15:58
I thought you would put the WHO link directly, this one https://www.who.int

**Comment by advayDev1** [comment] 2020-04-20 06:17
This is not a bug with this app.  Closing.

**Closed by advayDev1** 2020-04-20 06:17 UTC
Labels: area:docs
