### ISSUE TITLE
Content flickers in Russian on app startup

### ISSUE THREAD

**Issue by hspinks** [WorldHealthOrganization/app#766] opened 2020-04-01 03:48 UTC
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [x] Searched the [existing issues](https://github.com/WorldHealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [x] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

On app startup, content flickers in Russian initially before popping back to system default language.

**Comment by jamesblasco** [comment] 2020-04-02 00:13
Probably duplicate of [#776](https://github.com/WorldHealthOrganization/app/issues/776)

**Comment by hspinks** [comment] 2020-04-02 01:18
Assigning @advayDev1 to make English the first language in the localization array - won't fix bug entirely, but will solve the `P0` for now

**Comment by advayDev1** [comment] 2020-04-03 22:43
Dan fixed this in #831

**Closed by advayDev1** 2020-04-03 22:43 UTC
Labels: P0, bug, client, i18n
