### ISSUE TITLE
Error shown in About the App page

### ISSUE THREAD

**Issue by ramuz108** [WorldHealthOrganization/app#889] opened 2020-04-05 14:28 UTC
**Please follow this checklist. Please check each appropriate box (put an 'x' or check it after creating the issue).**
- [ ] Searched the [existing issues](https://github.com/World
![Screenshot_1586096676](https://user-images.githubusercontent.com/26342942/78501058-b33aa500-7777-11ea-9067-380a0bf633dd.png)
HealthOrganization/app/issues) to ensure you are not creating a duplicate.
- [ ] Followed the [Contributor Guidelines](https://github.com/WorldHealthOrganization/app/blob/master/docs/CONTRIBUTING.md).

**Comment by britannio** [comment] 2020-04-05 15:05
Duplicate of https://github.com/WorldHealthOrganization/app/issues/779
Please follow the checklist!

**Closed** 2020-04-05 15:05 UTC
Labels: duplicate
